In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
a @ b

40

In [3]:
import tensorflow as tf

class DuplicateLayer(tf.keras.layers.Layer):
    def __init__(self):
        super(DuplicateLayer, self).__init__()

    def call(self, inputs):
        return tf.concat([inputs, inputs], axis=-1)

# Test the custom layer
input_data = tf.constant([[1, 3, 3, 4, 5]], dtype=tf.float32)
custom_layer = DuplicateLayer()
output_data = custom_layer(input_data)
print(output_data)


tf.Tensor([[1. 3. 3. 4. 5. 1. 3. 3. 4. 5.]], shape=(1, 10), dtype=float32)


In [8]:
import numpy as np 

z = np.array([[[1, 2, 3], [2, 4, 5], [6, 4, 3]], [[1, 2, 3], [2, 4, 5], [6, 4, 3]]])

print(z)
print(np.shape(z))
print(z[1, 2])
print(z[1][2])

[[[1 2 3]
  [2 4 5]
  [6 4 3]]

 [[1 2 3]
  [2 4 5]
  [6 4 3]]]
(2, 3, 3)
[6 4 3]
[6 4 3]
